import {
  FileText,
  Image,
  FolderArchive,
  KeyRound,
  Sheet,
  AudioLines,
  Scissors,
  Combine,
  FileOutput,
  RotateCw,
  ScanLine,
  LockKeyhole,
  UnlockKeyhole,
  FileCode2,
  Scaling,
  Repeat2,
  LayoutGrid,
  PackageOpen,
  Package,
  Split,
  Merge,
  FileSpreadsheet,
  Table2,
  Mic,
  Volume2,
  Music2,
} from "lucide-react";
export const categories = [
  {
    id: "pdf",
    name: "PDF",
    subtitle: "Make your documents work for you.",
    short: "Split, merge, and make changes",
    icon: FileText,
    color: "rose",
  },
  {
    id: "image",
    name: "Photos",
    subtitle: "A few simple touches for your photos.",
    short: "Resize, convert, and combine",
    icon: Image,
    color: "blue",
  },
  {
    id: "file",
    name: "Files",
    subtitle: "Big files. Small effort.",
    short: "Zip, unzip, and split files",
    icon: FolderArchive,
    color: "amber",
  },
  {
    id: "password",
    name: "Passwords",
    subtitle: "A stronger password, in a second.",
    short: "Strong, random, or memorable",
    icon: KeyRound,
    color: "purple",
  },
  {
    id: "sheet",
    name: "Spreadsheets",
    subtitle: "Get your tables into shape.",
    short: "Convert and combine spreadsheets",
    icon: Sheet,
    color: "green",
  },
  {
    id: "audio",
    name: "Audio",
    subtitle: "From sound to words. And back.",
    short: "Convert, transcribe, and read aloud",
    icon: AudioLines,
    color: "orange",
  },
] as const;
export const tools = [
  {
    id: "pdf-split",
    category: "pdf",
    name: "Split PDF",
    description: "Save pages as separate PDFs",
    icon: Scissors,
    action: "Split PDF",
    accept: ["pdf"],
  },
  {
    id: "pdf-merge",
    category: "pdf",
    name: "Merge PDFs",
    description: "Bring documents together",
    icon: Combine,
    action: "Merge PDFs",
    accept: ["pdf"],
    multiple: true,
  },
  {
    id: "pdf-extract",
    category: "pdf",
    name: "Extract a page",
    description: "Keep just the page you need",
    icon: FileOutput,
    action: "Save page",
    accept: ["pdf"],
  },
  {
    id: "pdf-rotate",
    category: "pdf",
    name: "Rotate pages",
    description: "Get everything the right way up",
    icon: RotateCw,
    action: "Rotate pages",
    accept: ["pdf"],
  },
  {
    id: "pdf-redact",
    category: "pdf",
    name: "Redact a PDF",
    description: "Permanently remove private details",
    icon: ScanLine,
    action: "Save redacted PDF",
    accept: ["pdf"],
  },
  {
    id: "pdf-protect",
    category: "pdf",
    name: "Add a password",
    description: "Keep a document private",
    icon: LockKeyhole,
    action: "Protect PDF",
    accept: ["pdf"],
  },
  {
    id: "pdf-unlock",
    category: "pdf",
    name: "Remove a password",
    description: "Unlock using the current password",
    icon: UnlockKeyhole,
    action: "Save unlocked PDF",
    accept: ["pdf"],
  },
  {
    id: "pdf-markdown",
    category: "pdf",
    name: "PDF to Markdown",
    description: "Save text, tables, and images",
    icon: FileCode2,
    action: "Convert to Markdown",
    accept: ["pdf"],
  },
  {
    id: "image-resize",
    category: "image",
    name: "Resize photos",
    description: "Make photos the size you need",
    icon: Scaling,
    action: "Resize photos",
    accept: ["jpg", "jpeg", "png", "webp", "heic", "heif", "bmp", "tiff"],
    multiple: true,
  },
  {
    id: "image-convert",
    category: "image",
    name: "Convert photos",
    description: "Change to JPG, PNG, or WebP",
    icon: Repeat2,
    action: "Convert photos",
    accept: ["jpg", "jpeg", "png", "webp", "heic", "heif", "bmp", "tiff"],
    multiple: true,
  },
  {
    id: "image-collage",
    category: "image",
    name: "Make a collage",
    description: "Your favorite photos, together",
    icon: LayoutGrid,
    action: "Save collage",
    accept: ["jpg", "jpeg", "png", "webp", "heic", "heif"],
    multiple: true,
  },
  {
    id: "file-zip",
    category: "file",
    name: "Create a ZIP",
    description: "Bundle files for easy sharing",
    icon: Package,
    action: "Create ZIP",
    accept: [],
    multiple: true,
  },
  {
    id: "file-unzip",
    category: "file",
    name: "Unzip a file",
    description: "Unpack the files inside",
    icon: PackageOpen,
    action: "Unzip file",
    accept: ["zip"],
  },
  {
    id: "file-split",
    category: "file",
    name: "Split a large file",
    description: "Divide a file into smaller parts",
    icon: Split,
    action: "Split file",
    accept: [],
  },
  {
    id: "file-join",
    category: "file",
    name: "Rejoin file parts",
    description: "Put a split file back together",
    icon: Merge,
    action: "Rejoin file",
    accept: ["json"],
  },
  {
    id: "password",
    category: "password",
    name: "Generate a password",
    description: "Strong, random, or easy to remember",
    icon: KeyRound,
    action: "Generate password",
    accept: [],
  },
  {
    id: "sheet-csv",
    category: "sheet",
    name: "Excel to CSV",
    description: "Save each sheet as a CSV file",
    icon: Table2,
    action: "Convert to CSV",
    accept: ["xlsx"],
    multiple: true,
  },
  {
    id: "sheet-merge",
    category: "sheet",
    name: "Combine workbooks",
    description: "One workbook, separate tabs",
    icon: Combine,
    action: "Combine workbooks",
    accept: ["xlsx"],
    multiple: true,
  },
  {
    id: "sheet-excel",
    category: "sheet",
    name: "CSV to Excel",
    description: "Turn data into a tidy spreadsheet",
    icon: FileSpreadsheet,
    action: "Convert to Excel",
    accept: ["csv", "tsv"],
    multiple: true,
  },
  {
    id: "audio-mp3",
    category: "audio",
    name: "Video to MP3",
    description: "Keep the audio from your video",
    icon: Music2,
    action: "Save MP3",
    accept: ["mp4", "mov", "m4v", "webm"],
  },
  {
    id: "audio-transcribe",
    category: "audio",
    name: "Audio to text",
    description: "Turn a recording into a transcript",
    icon: Mic,
    action: "Transcribe",
    accept: ["mp3", "wav", "m4a", "mp4", "ogg", "flac"],
  },
  {
    id: "audio-speak",
    category: "audio",
    name: "Text to speech",
    description: "Give your words a voice",
    icon: Volume2,
    action: "Read aloud",
    accept: [],
  },
];
export type Tool = (typeof tools)[number];
export type LocalFile = { path: string; name: string; size?: number };
export type Result = {
  files?: string[];
  folder?: string;
  text?: string;
  warning?: string;
  password?: string;
  preview?: string;
  width?: number;
  height?: number;
  pages?: number;
  page?: number;
};
export type JobEvent = Result & {
  event: string;
  message?: string;
  code?: string;
  percent?: number | null;
  jobId?: string;
};
